### ISSUE TITLE
Remove scroll from whole app to individual scrollable components

### ISSUE THREAD

**Issue by nabramow** [Couchers-org/couchers#5070]
We have scroll set to the whole app rather than just in the scrollable components. This means even the nav bar scrolls, which is not what we want.

See what I mean on desktop here:

![ScreenRecording2024-10-27at6 46 19PM-ezgif com-video-to-gif-converter](https://github.com/user-attachments/assets/f3d8937f-dfaa-4533-8c56-4287292ae95d)

On mobile here:

![ScreenRecording2024-10-27at11 38 40AM-ezgif com-video-to-gif-converter](https://github.com/user-attachments/assets/0e7d84d1-8cd5-4054-a094-2718d7d13614)

We should add `overflow: "hidden" to the global html and body css in `AppRoute.tsx` like this:

```css
  "@global html": {
    scrollPaddingTop: `calc(${theme.shape.navPaddingXs} + ${theme.spacing(2)})`,
    height: "100%",
    overflow: "hidden" // here
  },
  [theme.breakpoints.up("sm")]: {
    "@global html": {
      scrollPaddingTop: `calc(${theme.shape.navPaddingSmUp} + ${theme.spacing(
        2
      overflow: "hidden" // here
      )})`,
    },
  },
  "@global body": {
    height: "100%",
    overflow: "hidden" // here
  },
```

Right now that breaks the scroll in other places, so the main part of this ticket will be adding the `overflow: "auto"` to the specific components that should have it (below the nav bar) after making this change. For example the dashboard landing page no longer scrolls.

Make sure to check mobile and desktop.
